language: ruby
rvm: 2.4.1
before_script:
- gem install awesome_bot
- gem install mdl
script:
- awesome_bot README.md --allow-dupe -w jinja.pocoo.org,vimeo.com # Allow duplicate links and whitelist jinja.pocoo.org
- mdl --rules ~MD013,~MD033 README.md # Ignore line length (MD013) and inline HTML (MD033) Rules
notifications:
  email: false
